### ISSUE TITLE
js 实现打字机效果

### ISSUE THREAD

**Issue by jtwang7** [jtwang7/Project-Note#2]
# js 实现打字机效果
参考文章：[5行代码带你实现一个js的打字效果](https://juejin.cn/post/6844904006460899335)

## 5 行代码实现
```js
const dom = document.querySelector('.content') // 获取容器元素
const data = '最简单的打字效果代码'.split('') // 分离文本
let index = 0 // 指针
function writing(index) {
    if (index < data.length) {
        dom.innerHTML += data[index]
        setTimeout(writing.bind(this), 200, ++index)
    }
}
```

## 原理
通过 setTimeout 设置一个时间的间隔， 每隔一定时间向 dom 容器中插入下一个字符， 并后移指针， 然后重新调用函数设定下一次计时器。
> 如果对时间精度要求不是特别高的话，也可以使用 setInterval 来执行字符插入。

## 拓展：模拟闪烁光标
通过一个伪类 after， 将光标定在 dom 容器样式后面， 并给一个显示隐藏的循环动画模拟光标的闪烁。
```css
.content::after{
    content: '|';
    animation: blink 1s infinite
}
@keyframes blink{
    from{
        opacity: 0;
    }
    to{
        opacity: 1;
    }
}
```
> 伪类与容器类名间不用空格分开，表示该伪类是附属在该类名后面的。
